### PR TITLE
Allow numeric literal as property name

### PR DESCRIPTION
**Pull request by bleis-tift**
related: #35

### CODE REVIEW

**Comment by sjrd** [comment]
This should probably be revisited after #47, as there will be conflicts with the code there, and some of the same comments apply here.

**Comment by sjrd** [comment]
#47 has now been merged, so this can now be rebased on top of master to address the conflicts and adapt to the `IntLiteral`/`DoubleLiteral` from #47.

**Comment by sjrd** [comment]
The `.ts` files in the tests will also need to be renamed to `.d.ts` to adapt to the changes in #56.

**Comment by bleis-tift** [comment]
rebased.

**Pull request merged**
